//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSLocationVoiture
{
    using System;
    using System.Collections.Generic;
    
    public partial class voiture
    {
        public int id { get; set; }
        public string name { get; set; }
        public string adresse { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public byte[] image { get; set; }
    }
}
